server:
  port: 9000
spring:
  application:
    name: coupon-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
zuul:
  prefix: /imooc
  routes:
    # 优惠券模板微服务路由配置
    template:
      path: /coupon-template/** #来自template微服务yml中的context-path: /coupon-template
      serviceId: eureka-client-coupon-template #来自template微服务yml中的name: eureka-client-coupon-template
      strip-prefix: false
    host:
      connect-timeout-millis: 15000
      socket-timeout-millis: 60000

ribbon:
  ConnectTimeout: 15000
  ReadTimeout: 15000